// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8RlTdo8lYmQMzZ_JhMDj-d7u6xyxGRG4',
    appId: '1:330713263171:web:6561a679d984037a18f8f6',
    messagingSenderId: '330713263171',
    projectId: 'fiotest-4c53a',
    authDomain: 'fiotest-4c53a.firebaseapp.com',
    storageBucket: 'fiotest-4c53a.firebasestorage.app',
    measurementId: 'G-3958XXBTM6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIIUifSfb-gS5Nx66CCTSTfrCzgV_5tZ4',
    appId: '1:330713263171:android:0bf14f50f6c4de9318f8f6',
    messagingSenderId: '330713263171',
    projectId: 'fiotest-4c53a',
    storageBucket: 'fiotest-4c53a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcubUvhGvA9N6j_olXh8BWxrP9mh3zYx8',
    appId: '1:330713263171:ios:1eb9fbd84e67138a18f8f6',
    messagingSenderId: '330713263171',
    projectId: 'fiotest-4c53a',
    storageBucket: 'fiotest-4c53a.firebasestorage.app',
    iosBundleId: 'com.nalbantsoft.lojistik',
  );

}