// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYri95yAhSUEZdpZTYzQl3_QS08BBO_bM',
    appId: '1:462304492570:web:871d8448180d3d6e0e25a3',
    messagingSenderId: '462304492570',
    projectId: 'muallim-a34e4',
    authDomain: 'muallim-a34e4.firebaseapp.com',
    storageBucket: 'muallim-a34e4.firebasestorage.app',
    measurementId: 'G-RTP1PBVCWD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOvm-oRXOrLAUYPyGnQqdKKuccrV3brW4',
    appId: '1:462304492570:android:0574e072de5254fe0e25a3',
    messagingSenderId: '462304492570',
    projectId: 'muallim-a34e4',
    storageBucket: 'muallim-a34e4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKCQaLjHUc6x8CV0b9S-AcrvVSwJqPcvU',
    appId: '1:462304492570:ios:172f45ce12d5d3550e25a3',
    messagingSenderId: '462304492570',
    projectId: 'muallim-a34e4',
    storageBucket: 'muallim-a34e4.firebasestorage.app',
    iosBundleId: 'com.nalbantsoft.lojistik',
  );
}
